<?php

namespace Tests\Marketing\Product\Catalog;

use Verybuy\Marketing\Product\Catalog\Factory\MarketingFactory;
use Verybuy\Marketing\Product\Catalog\Adapter\AdapterContract;

class GoogleAdapterTest extends AbstractTestCase
{
    protected $config;
    protected $resourceStub;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->config = [
            'title' => 'Verybuy Store',
            'link' => 'http://www.verybuy.cc'
        ];

        $this->resourceStub = [
            [
                'id' => '745130',
                'title' => '包郵大碼女內褲性感蕾絲面料透明網紗中腰三角褲包臀無痕提臀胖mm',
                'description' => '包郵大碼女內褲性感蕾絲面料透明網紗中腰三角褲包臀無痕提臀胖mm',
                'brand' => 'VeryBuy',
                'link' => 'http://www.verybuy.cc/user_submit/item/745130',
                'image_link' => 'http://img.verybuy.cc/taobao_user_submit/1a842d087b481d7cae79f76dda8fd5a6_600.jpg',
                'condition' => 'new',
                'availability' => 'in stock',
                'price' => 236,
                'product_type' => 1,
                'google_product_category' => 1,
                'custom_label_0' => 1,
                'custom_label_1' => 3,
                'custom_label_2' => 'custom_label_2',
                'custom_label_3' => 'custom_label_3',
                'custom_label_4' => 'custom_label_4',
//                'shipping' => [
//                    'country' => 'TW',
//                    'service' => 'Standard',
//                    'price' => '236 TWD',
//                ]
            ],
            [
                'id' => '745123',
                'title' => '一片式無肩帶內衣聚攏防滑隱形婚紗禮服專用美背小胸加厚文胸套裝',
                'description' => '一片式無肩帶內衣聚攏防滑隱形婚紗禮服專用美背小胸加厚文胸套裝',
                'price' => 409,
                'brand' => 'VeryBuy',
                'link' => 'http://www.verybuy.cc/user_submit/item/745123',
                'image_link' => 'http://img.verybuy.cc/taobao_user_submit/679711600f1339ad421e96c571290cda_600.jpg',
                'condition' => 'new',
                'adult' => 'yes',
                'availability' => 'in stock',
                'product_type' => 1,
                'google_product_category' => 1,
                'custom_label_0' => 1,
                'custom_label_1' => 3,
                'custom_label_2' => 'custom_label_2',
                'custom_label_3' => 'custom_label_3',
                'custom_label_4' => 'custom_label_4',
//                'shipping' => [
//                    'country' => 'TW',
//                    'service' => 'Standard',
//                    'price' => '236 TWD',
//                ]
            ],
        ];
    }

    public function testRenderXML()
    {
        $xml = MarketingFactory::create(AdapterContract::GOOGLE)
            ->config($this->config)
            ->import($this->resourceStub)
             ->toXml()
        ;
//        dump($xml);
        //@todo xml assert
    }

    public function testAdapterSetConfig()
    {
        /**
         * @todo set adapter config
         */
    }

    public function testAdapterImport()
    {
        /**
         * @todo assert success resource
         */

        /**
         * @todo assert failure resource
         */
    }
}
