<?php

namespace Tests\Marketing\Product\Catalog;

use Verybuy\Marketing\Product\Catalog\Factory\MarketingFactory;
use Verybuy\Marketing\Product\Catalog\Adapter\AdapterContract;

class GoogleAdapterTest extends AbstractTestCase
{
    protected $config;
    protected $resourceStub;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->config = [
            'title' => 'Verybuy Store',
            'link' => 'http://www.verybuy.cc'
        ];

        $this->resourceStub = [
            [
                'id' => '9166976',
                'title' => '羽絨馬甲女秋冬中長款大碼服裝韓版連帽背心顯瘦棉坎肩修身馬夾女#9166976',
                'description' => '羽絨馬甲女秋冬中長款大碼服裝韓版連帽背心顯瘦棉坎肩修身馬夾女#9166976',
                'brand' => 'VeryBuy',
                'link' => 'http://www.verybuy.cc/user_submit/item/9166976',
                'image_link' => 'http://img.ssl.verybuy.cc/taobao_user_submit/8cd753871468887989de503d078aac0e.jpg',
                'condition' => 'new',
                'availability' => 'in stock',
                'price' => '1069 TWD',
                'product_type' => 20,
                'google_product_category' => 166,
                'custom_label_0' => 1,
                'custom_label_1' => 1,
                'custom_label_2' => '羽絨馬甲女秋冬中長款大碼服裝韓版連帽背心顯瘦棉坎肩修身馬夾女',
                'custom_label_3' => '',
                'custom_label_4' => '',
                // 'shipping' => [
                //     'country' => 'TW',
                //     'service' => 'Standard',
                //     'price' => '236 TWD',
                // ]
            ],
            [
                'id' => '9166985',
                'title' => '2015秋裝新款公主修身大碼秋天蓬蓬裙伴娘小禮服冬季打底連衣裙厚#9166985',
                'description' => '2015秋裝新款公主修身大碼秋天蓬蓬裙伴娘小禮服冬季打底連衣裙厚#9166985',
                'brand' => 'VeryBuy',
                'link' => 'http://www.verybuy.cc/user_submit/item/9166985',
                'image_link' => 'http://img.ssl.verybuy.cc/taobao_user_submit/757916d333de33e6f7de3c5b0906b040.jpg',
                'condition' => 'new',
                'availability' => 'in stock',
                'price' => '851 TWD',
                'product_type' => 14,
                'google_product_category' => 166,
                'custom_label_0' => 10,
                'custom_label_1' => 1,
                'custom_label_2' => '羽絨馬甲女秋冬中長款大碼服裝韓版連帽背心顯瘦棉坎肩修身馬夾女',
                'custom_label_3' => '',
                'custom_label_4' => '',
                // 'shipping' => [
                //     'country' => 'TW',
                //     'service' => 'Standard',
                //     'price' => '236 TWD',
                // ]
            ],
        ];
    }

    public function testRenderXML()
    {
        $xml = MarketingFactory::create(AdapterContract::GOOGLE)
            ->config($this->config)
            ->import($this->resourceStub)
             ->toXml()
        ;
//        dump($xml);
        //@todo xml assert
    }

    public function testSaveCVS()
    {
        $csv = MarketingFactory::create(AdapterContract::FACEBOOK)
            ->config($this->config)
            ->import($this->resourceStub)
             ->saveCsv('vendor/file.csv')
        ;
    }

    public function testAdapterSetConfig()
    {
        /**
         * @todo set adapter config
         */
    }

    public function testAdapterImport()
    {
        /**
         * @todo assert success resource
         */

        /**
         * @todo assert failure resource
         */
    }
}
